name: Deploy My Hubitat to Azure Functios

on:
  push:
    branches: [main]
    paths:
      - "src/dotnet/MyHubitatFunc/**/*.*"
  pull_request:
    branches: [main]
    paths:
      - "src/dotnet/MyHubitatFunc/**/*.*"

env:
  AZURE_FUNCTIONAPP_NAME: myty-hubitat
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "src/dotnet/MyHubitatFunc"
  DOTNET_VERSION: "3.1.406"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
